version: '3'
services:
    redis:
        image: redis:latest
        container_name: redisDB
        ports:
            - 6379:6379
        volumes:
            - .\redis-conf\redis.conf:/usr/local/etc/redis/redis.conf
        command: [ "redis-server"]
